---
# tasks/main.yml: Main tasks file for ansible-ubuntu-devbox

- name: Create ~/.gnupg
  file:
    path: "{{ ubuntu_devbox_home_dir }}/.gnupg"
    state: directory
    mode: 0700
    force: yes
  tags:
    - git_conf

- name: Instal gpg key to sign git commits
  copy:
    src: "~/.gnupg/{{ ubuntu_devbox_gpg_keyid }}.key"
    dest: "{{ ubuntu_devbox_home_dir }}/.gnupg/{{ ubuntu_devbox_gpg_keyid }}.key"
    mode: 0600
  tags:
    - git_conf

# this command raises an error when key already imported -> ignore it
# gpg: key xxx: already in secret keyring
# gpg: Total number processed: 1
# gpg:       secret keys read: 1
# gpg:  secret keys unchanged: 1
- name: Add gpg key
  shell: "gpg --import {{ ubuntu_devbox_home_dir }}/.gnupg/{{ ubuntu_devbox_gpg_keyid }}.key || true"
  tags:
    - git_conf

- name: Fetch dotfiles
  git:
    repo: https://github.com/ebreton/dotfiles.git
    dest: "{{ ubuntu_devbox_dotfiles_dir }}"
  tags:
    - user_environment

- name: Execute dotfiles bootstrap
  shell: "{{ ubuntu_devbox_dotfiles_dir }}/bootstrap.sh --force >> {{ ubuntu_devbox_home_dir }}/bootstrap.out"
  tags:
    - user_environment

- name: Setup .extra in user account
  template:
    src: templates/.extra
    dest: "{{ ubuntu_devbox_home_dir }}/.extra"
    force: yes
  tags:
    - user_environment

- name: Extend global config for git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - { "name": "user.name", "value": "{{ ubuntu_devbox_git_authorname }}" }
    - { "name": "user.email", "value": "{{ ubuntu_devbox_git_authoremail }}" }
    - { "name": "user.signingkey", "value": "{{ ubuntu_devbox_gpg_keyid }}" }
  tags:
    - git_conf

- name: Fetch bash-git-prompt
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: .bash-git-prompt
    depth: 1
  tags:
    - user_environment

- name: Fetch helpers github repos
  git:
    repo: "https://github.com/Cortexia-CH/{{ item }}.git"
    dest: "{{ ubuntu_devbox_src_dir }}/{{ item }}"
    accept_hostkey: True
  with_items: "{{ ubuntu_cortexia_github_repos }}"
  tags:
    - user_environment
    - git_repos


- name: Fetch helpers bitbucket repos
  git:
    repo: "git@bitbucket.org:cortexiacci/{{ item }}.git"
    dest: "{{ ubuntu_devbox_src_dir }}/{{ item }}"
    accept_hostkey: True
  with_items: "{{ ubuntu_cortexia_bitbucket_repos }}"
  tags:
    - user_environment
    - git_repos
