---
# tasks/main.yml: Main tasks file for ansible-ubuntu-devbox

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
  tags:
    - update
    - os_packages

- name: Install OS packages
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items: "{{ ubuntu_devbox_os_packages }}"
  tags:
    - update
    - os_packages

- name: Add Docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present
  tags:
    - os_packages
    - docker

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  tags:
    - os_packages
    - docker

- name: Install OS packages
  apt:
    update_cache: yes
    name: "docker-ce"
  tags:
    - os_packages
    - docker

- name: Enable (and start) docker service
  systemd:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker

- name: Update pip
  pip:
    name: pip
    extra_args: --upgrade
  tags:
    - update
    - python_packages
    - docker

- name: Python packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ubuntu_devbox_python_packages }}"
  tags:
    - python_packages
    - docker

- name: Download Go archive
  get_url: "url={{ ubuntu_devbox_go_urlbase }}/{{ ubuntu_devbox_go_archive }} dest=/tmp/{{ ubuntu_devbox_go_archive }} sha256sum={{ ubuntu_devbox_go_sha256sum }}"
  tags:
    - go_packages

- name: Unpack Go archive
  unarchive:
    src: "/tmp/{{ ubuntu_devbox_go_archive }}"
    dest: "{{ ubuntu_devbox_go_root }}"
    copy: no
  tags:
    - go_packages

- name: Create user account
  user: "name={{ ubuntu_devbox_user }} password={{ ubuntu_devbox_passwd }} home={{ ubuntu_devbox_home_dir }} comment='{{ ubuntu_devbox_comment }}' shell={{ ubuntu_devbox_shell }} groups=sudo append=yes"
  tags:
    - user_account

- name: Add user to docker group
  user:
    name: "{{ ubuntu_devbox_user }}"
    groups: docker
    append: yes
  tags:
    - user_account
    - docker

- name: Create ssh dir
  file: "path={{ ubuntu_devbox_home_dir }}/.ssh state=directory owner={{ ubuntu_devbox_user }} group={{ ubuntu_devbox_user }} mode=0700"
  tags:
    - user_account

- name: Install ssh authorized_keys
  copy:
    src: authorized_keys
    dest: "{{ ubuntu_devbox_home_dir }}/.ssh/authorized_keys"
    owner: "{{ ubuntu_devbox_user }}"
    group: "{{ ubuntu_devbox_user }}"
    mode: "0600"
  tags:
    - user_account

- name: update all images and all repos
  command: /home/emb/bin/pullall.sh both *
  args:
    chdir: /home/emb/git-repos
  tags:
    - update
