---
# tasks/main.yml: Main tasks file for ansible-ubuntu-devbox

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
  tags:
    - update
    - os_packages

- name: Install OS packages
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items: "{{ ubuntu_devbox_os_packages }}"
  tags:
    - os_packages

- name: "Python packages"
  become: True
  become_method: sudo
  pip:
    name: "{{ item }}"
  with_items: "{{ ubuntu_devbox_python_packages }}"
  tags:
    - python_packages

- name: Create user account
  user: "name={{ ubuntu_devbox_user }} password={{ ubuntu_devbox_passwd }} home={{ ubuntu_devbox_home_dir }} comment='{{ ubuntu_devbox_comment }}' shell={{ ubuntu_devbox_shell }} groups=sudo append=yes"
  tags:
    - user_account

- name: Create ssh dir
  file: "path={{ ubuntu_devbox_home_dir }}/.ssh state=directory owner={{ ubuntu_devbox_user }} group={{ ubuntu_devbox_user }} mode=0700"
  tags:
    - user_account

- name: Install ssh authorized_keys
  copy: "src=authorized_keys dest={{ ubuntu_devbox_home_dir }}/.ssh/authorized_keys owner={{ ubuntu_devbox_user }} group={{ ubuntu_devbox_user }} mode=0600"
  tags:
    - user_account

- name: Download Go archive
  get_url: "url={{ ubuntu_devbox_go_urlbase }}/{{ ubuntu_devbox_go_archive }} dest=/tmp/{{ ubuntu_devbox_go_archive }} sha256sum={{ ubuntu_devbox_go_sha256sum }}"
  tags:
    - go_packages

- name: Unpack Go archive
  unarchive:
    src: "/tmp/{{ ubuntu_devbox_go_archive }}"
    dest: "{{ ubuntu_devbox_go_root }}"
    copy: no
  tags:
    - go_packages

- name: Fetch dotfiles
  git: "repo=https://github.com/ebreton/dotfiles.git dest={{ ubuntu_devbox_dotfiles_dir }} accept_hostkey=yes"
  tags:
    - user_environment

- name: Home ownership
  file: "path={{ ubuntu_devbox_home_dir }} owner={{ ubuntu_devbox_user }} group={{ ubuntu_devbox_user }} recurse=yes"
  tags:
    - user_account
    - user_environment

- name: Execute dotfiles bootstrap
  become: True
  become_user: "{{ ubuntu_devbox_user }}"
  shell: "{{ ubuntu_devbox_dotfiles_dir }}/bootstrap.sh --force >> {{ ubuntu_devbox_home_dir }}/bootstrap.out"
  tags:
    - user_environment

